version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nbp_postgress
    restart: always
    environment:
      POSTGRES_DB: nbp_exchange        
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./fastAPI
    container_name: nbp_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./currenciesFrontend/currencies
      dockerfile: Dockerfile
    container_name: nbp_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
